/*
 * List of All Creatures to be used to determine whether creature or player
 * Credits goes to brunelli1989
*/


using System.Collections.Generic;
using Pokemon.Objects;

namespace Pokemon.Constants
{
    public static class CreatureLists
    {
        #region All Creatures
        public static Dictionary<string, CreatureData> AllCreatures = new Dictionary<string, CreatureData>
        { 
        { Creatures.Abra.Name, Creatures.Abra },
        { Creatures.Aerodactyl.Name, Creatures.Aerodactyl },
        { Creatures.Aipom.Name, Creatures.Aipom },
        { Creatures.Alakazam.Name, Creatures.Alakazam },
        { Creatures.Ampharos.Name, Creatures.Ampharos },
        { Creatures.Arbok.Name, Creatures.Arbok },
        { Creatures.Arcanine.Name, Creatures.Arcanine },
        { Creatures.Ariados.Name, Creatures.Ariados },
        { Creatures.Articuno.Name, Creatures.Articuno },
        { Creatures.Azumarill.Name, Creatures.Azumarill },
        { Creatures.Bayleef.Name, Creatures.Bayleef },
        { Creatures.Beedrill.Name, Creatures.Beedrill },
        { Creatures.Bellossom.Name, Creatures.Bellossom },
        { Creatures.Bellsprout.Name, Creatures.Bellsprout },
        { Creatures.Blastoise.Name, Creatures.Blastoise },
        { Creatures.Blissey.Name, Creatures.Blissey },
        { Creatures.Bulbasaur.Name, Creatures.Bulbasaur },
        { Creatures.Butterfree.Name, Creatures.Butterfree },
        { Creatures.Caterpie.Name, Creatures.Caterpie },
        { Creatures.Celebi.Name, Creatures.Celebi },
        { Creatures.Chansey.Name, Creatures.Chansey },
        { Creatures.Charizard.Name, Creatures.Charizard },
        { Creatures.Charmander.Name, Creatures.Charmander },
        { Creatures.Charmeleon.Name, Creatures.Charmeleon },
        { Creatures.Chikorita.Name, Creatures.Chikorita },
        { Creatures.Chinchou.Name, Creatures.Chinchou },
        { Creatures.Clefable.Name, Creatures.Clefable },
        { Creatures.Clefairy.Name, Creatures.Clefairy },
        { Creatures.Cleffa.Name, Creatures.Cleffa },
        { Creatures.Cloyster.Name, Creatures.Cloyster },
        { Creatures.Corsola.Name, Creatures.Corsola },
        { Creatures.Crobat.Name, Creatures.Crobat },
        { Creatures.Croconaw.Name, Creatures.Croconaw },
        { Creatures.Cubone.Name, Creatures.Cubone },
        { Creatures.Cyndaquil.Name, Creatures.Cyndaquil },
        { Creatures.Delibird.Name, Creatures.Delibird },
        { Creatures.Dewgong.Name, Creatures.Dewgong },
        { Creatures.Diglett.Name, Creatures.Diglett },
        { Creatures.Ditto.Name, Creatures.Ditto },
        { Creatures.Dodrio.Name, Creatures.Dodrio },
        { Creatures.Doduo.Name, Creatures.Doduo },
        { Creatures.Donphan.Name, Creatures.Donphan },
        { Creatures.Dragonair.Name, Creatures.Dragonair },
        { Creatures.Dragonite.Name, Creatures.Dragonite },
        { Creatures.Dratini.Name, Creatures.Dratini },
        { Creatures.Drowzee.Name, Creatures.Drowzee },
        { Creatures.Dugtrio.Name, Creatures.Dugtrio },
        { Creatures.Dunsparce.Name, Creatures.Dunsparce },
        { Creatures.Eevee.Name, Creatures.Eevee },
        { Creatures.Ekans.Name, Creatures.Ekans },
        { Creatures.Electabuzz.Name, Creatures.Electabuzz },
        { Creatures.Electrode.Name, Creatures.Electrode },
        { Creatures.Elekid.Name, Creatures.Elekid },
        { Creatures.Entei.Name, Creatures.Entei },
        { Creatures.Espeon.Name, Creatures.Espeon },
        { Creatures.Exeggcute.Name, Creatures.Exeggcute },
        { Creatures.Exeggutor.Name, Creatures.Exeggutor },
        { Creatures.Farfetchd.Name, Creatures.Farfetchd },
        { Creatures.Fearow.Name, Creatures.Fearow },
        { Creatures.Feraligatr.Name, Creatures.Feraligatr },
        { Creatures.Flaaffy.Name, Creatures.Flaaffy },
        { Creatures.Flareon.Name, Creatures.Flareon },
        { Creatures.Forretress.Name, Creatures.Forretress },
        { Creatures.Furret.Name, Creatures.Furret },
        { Creatures.Gastly.Name, Creatures.Gastly },
        { Creatures.Gengar.Name, Creatures.Gengar },
        { Creatures.Geodude.Name, Creatures.Geodude },
        { Creatures.Girafarig.Name, Creatures.Girafarig },
        { Creatures.Gligar.Name, Creatures.Gligar },
        { Creatures.Gloom.Name, Creatures.Gloom },
        { Creatures.Golbat.Name, Creatures.Golbat },
        { Creatures.Goldeen.Name, Creatures.Goldeen },
        { Creatures.Golduck.Name, Creatures.Golduck },
        { Creatures.Golem.Name, Creatures.Golem },
        { Creatures.Granbull.Name, Creatures.Granbull },
        { Creatures.Graveler.Name, Creatures.Graveler },
        { Creatures.Grimer.Name, Creatures.Grimer },
        { Creatures.Growlithe.Name, Creatures.Growlithe },
        { Creatures.Gyarados.Name, Creatures.Gyarados },
        { Creatures.Haunter.Name, Creatures.Haunter },
        { Creatures.Heracross.Name, Creatures.Heracross },
        { Creatures.Hitmonchan.Name, Creatures.Hitmonchan },
        { Creatures.Hitmonlee.Name, Creatures.Hitmonlee },
        { Creatures.Hitmontop.Name, Creatures.Hitmontop },
        { Creatures.Hooh.Name, Creatures.Hooh },
        { Creatures.Hoothoot.Name, Creatures.Hoothoot },
        { Creatures.Hoppip.Name, Creatures.Hoppip },
        { Creatures.Horsea.Name, Creatures.Horsea },
        { Creatures.Houndoom.Name, Creatures.Houndoom },
        { Creatures.Houndour.Name, Creatures.Houndour},
        { Creatures.Hypno.Name, Creatures.Hypno },
        { Creatures.Igglybuff.Name, Creatures.Igglybuff },
        { Creatures.Ivysaur.Name, Creatures.Ivysaur },
        { Creatures.Jigglypuff.Name, Creatures.Jigglypuff },
        { Creatures.Jolteon.Name, Creatures.Jolteon },
        { Creatures.Jolteon.Name, Creatures.Jolteon },
        { Creatures.Jumpluff.Name, Creatures.Jumpluff },
        { Creatures.Jynx.Name, Creatures.Jynx },
        { Creatures.Kabuto.Name, Creatures.Kabuto },
        { Creatures.Kadabra.Name, Creatures.Kadabra },
        { Creatures.Kakuna.Name, Creatures.Kakuna },
        { Creatures.Kangaskhan.Name, Creatures.Kangaskhan },
        { Creatures.Kingdra.Name, Creatures.Kingdra },
        { Creatures.Kingler.Name, Creatures.Kingler },
        { Creatures.Koffing.Name, Creatures.Koffing },
        { Creatures.Krabby.Name, Creatures.Krabby },
        { Creatures.Lanturn.Name, Creatures.Lanturn },
        { Creatures.Lapras.Name, Creatures.Lapras },
        { Creatures.Larvitar.Name, Creatures.Larvitar },
        { Creatures.Ledian.Name, Creatures.Ledian },
        { Creatures.Ledyba.Name, Creatures.Ledyba },
        { Creatures.Lickitung.Name, Creatures.Lickitung },
        { Creatures.Lugia.Name, Creatures.Lugia },
        { Creatures.Machamp.Name, Creatures.Machamp },
        { Creatures.Machoke.Name, Creatures.Machoke },
        { Creatures.Machop.Name, Creatures.Machop },
        { Creatures.Magby.Name, Creatures.Magby },
        { Creatures.Magcargo.Name, Creatures.Magcargo},
        { Creatures.Magikarp.Name, Creatures.Magikarp},
        { Creatures.Magmar.Name, Creatures.Magmar},
        { Creatures.Magnemite.Name, Creatures.Magnemite},
        { Creatures.Magneton.Name, Creatures.Magneton},
        { Creatures.Mankey.Name, Creatures.Mankey},
        { Creatures.Mantine.Name, Creatures.Mantine},
        { Creatures.Mareep.Name, Creatures.Mareep},
        { Creatures.Marill.Name, Creatures.Marill},
        { Creatures.Marowak.Name, Creatures.Marowak},
        { Creatures.Meganium.Name, Creatures.Meganium},
        { Creatures.Meowth.Name, Creatures.Meowth},
        { Creatures.Metapod.Name, Creatures.Metapod},
        { Creatures.Mew.Name, Creatures.Mew},
        { Creatures.Mewtwo.Name, Creatures.Mewtwo},
        { Creatures.Miltank.Name, Creatures.Miltank},
        { Creatures.Misdreavus.Name, Creatures.Misdreavus},
        { Creatures.Moltres.Name, Creatures.Moltres},
        { Creatures.MrMime.Name, Creatures.MrMime},
        { Creatures.Muk.Name, Creatures.Muk},
        { Creatures.Murkrow.Name, Creatures.Murkrow},
        { Creatures.Natu.Name, Creatures.Natu},
        { Creatures.Nidoking.Name, Creatures.Nidoking},
        { Creatures.Nidoqueen.Name, Creatures.Nidoqueen},
        { Creatures.NidoranMa.Name, Creatures.NidoranMa},
        { Creatures.NidoranFe.Name, Creatures.NidoranFe},
        { Creatures.Nidorina.Name, Creatures.Nidorina},
        { Creatures.Nidorino.Name, Creatures.Nidorino},
        { Creatures.Ninetales.Name, Creatures.Ninetales},
        { Creatures.Noctowl.Name, Creatures.Noctowl},
        { Creatures.Octillery.Name, Creatures.Octillery},
        { Creatures.Oddish.Name, Creatures.Oddish},
        { Creatures.Omanyte.Name, Creatures.Omanyte},
        { Creatures.Omastar.Name, Creatures.Omastar},
        { Creatures.Onix.Name, Creatures.Onix},
        { Creatures.Paras.Name, Creatures.Paras},
        { Creatures.Parasect.Name, Creatures.Parasect},
        { Creatures.Persian.Name, Creatures.Persian},
        { Creatures.Phanpy.Name, Creatures.Phanpy},
        { Creatures.Pichu.Name, Creatures.Pichu},
        { Creatures.Pidgeot.Name, Creatures.Pidgeot},
        { Creatures.Pidgey.Name, Creatures.Pidgey},
        { Creatures.Pidgotto.Name, Creatures.Pidgotto},
        { Creatures.Pikachu.Name, Creatures.Pikachu},
        { Creatures.Piloswine.Name, Creatures.Piloswine},
        { Creatures.Pineco.Name, Creatures.Pineco},
        { Creatures.Pinsir.Name, Creatures.Pinsir},
        { Creatures.Politoed.Name, Creatures.Politoed},
        { Creatures.Poliwag.Name, Creatures.Poliwag},
        { Creatures.Poliwhirl.Name, Creatures.Poliwhirl},
        { Creatures.Poliwrath.Name, Creatures.Poliwrath},
        { Creatures.Ponyta.Name, Creatures.Ponyta},
        { Creatures.Ponyta.Name, Creatures.Ponyta},
        { Creatures.Porygon.Name, Creatures.Porygon},
        { Creatures.Porygon2.Name, Creatures.Porygon2},
        { Creatures.Primeape.Name, Creatures.Primeape},
        { Creatures.Psyduck.Name, Creatures.Psyduck},
        { Creatures.Pupitar.Name, Creatures.Pupitar},
        { Creatures.Quagsire.Name, Creatures.Quagsire},
        { Creatures.Quilava.Name, Creatures.Quilava},
        { Creatures.Qwilfish.Name, Creatures.Qwilfish},
        { Creatures.Raichu.Name, Creatures.Raichu},
        { Creatures.Raikou.Name, Creatures.Raikou},
        { Creatures.Rapidash.Name, Creatures.Rapidash},
        { Creatures.Raticate.Name, Creatures.Raticate},
        { Creatures.Rattata.Name, Creatures.Rattata},
        { Creatures.Remoraid.Name, Creatures.Remoraid},
        { Creatures.Rhydon.Name, Creatures.Rhydon},
        { Creatures.Rhyhorn.Name, Creatures.Rhyhorn},
        { Creatures.Sandshrew.Name, Creatures.Sandshrew},
        { Creatures.Sandslash.Name, Creatures.Sandslash},
        { Creatures.Scizor.Name, Creatures.Scizor},
        { Creatures.Scyther.Name, Creatures.Scyther},
        { Creatures.Seadra.Name, Creatures.Seadra},
        { Creatures.Seaking.Name, Creatures.Seaking},
        { Creatures.Seel.Name, Creatures.Seel},
        { Creatures.Sentret.Name, Creatures.Sentret},
        { Creatures.Shellder.Name, Creatures.Shellder},
        { Creatures.Shuckle.Name, Creatures.Shuckle},
        { Creatures.Skarmory.Name, Creatures.Skarmory},
        { Creatures.Skiploom.Name, Creatures.Skiploom},
        { Creatures.Slowbro.Name, Creatures.Slowbro},
        { Creatures.Slowking.Name, Creatures.Slowking},
        { Creatures.Slowpoke.Name, Creatures.Slowpoke},
        { Creatures.Slugma.Name, Creatures.Slugma},
        { Creatures.Smeargle.Name, Creatures.Smeargle},
        { Creatures.Smoochum.Name, Creatures.Smoochum},
        { Creatures.Sneasel.Name, Creatures.Sneasel},
        { Creatures.Snorlax.Name, Creatures.Snorlax},
        { Creatures.Snubbull.Name, Creatures.Snubbull},
        { Creatures.Spearow.Name, Creatures.Spearow},
        { Creatures.Spinarak.Name, Creatures.Spinarak},
        { Creatures.Squirtle.Name, Creatures.Squirtle},
        { Creatures.Stantler.Name, Creatures.Stantler},
        { Creatures.Starmie.Name, Creatures.Starmie},
        { Creatures.Staryu.Name, Creatures.Staryu},
        { Creatures.Steelix.Name, Creatures.Steelix},
        { Creatures.Sudowoodo.Name, Creatures.Sudowoodo},
        { Creatures.Suicune.Name, Creatures.Suicune},
        { Creatures.Sunflora.Name, Creatures.Sunflora},
        { Creatures.Sunkern.Name, Creatures.Sunkern},
        { Creatures.Swinub.Name, Creatures.Swinub},
        { Creatures.Tangela.Name, Creatures.Tangela},
        { Creatures.Tauros.Name, Creatures.Tauros},
        { Creatures.Teddiursa.Name, Creatures.Teddiursa},
        { Creatures.Tentacool.Name, Creatures.Tentacool},
        { Creatures.Tentacruel.Name, Creatures.Tentacruel},
        { Creatures.Togepi.Name, Creatures.Togepi},
        { Creatures.Togetic.Name, Creatures.Togetic},
        { Creatures.Totodile.Name, Creatures.Totodile},
        { Creatures.Typhlosion.Name, Creatures.Typhlosion},
        { Creatures.Tyranitar.Name, Creatures.Tyranitar},
        { Creatures.Tyrogue.Name, Creatures.Tyrogue},
        { Creatures.Umbreon.Name, Creatures.Umbreon},
        { Creatures.Unown.Name, Creatures.Unown},
        { Creatures.Ursaring.Name, Creatures.Ursaring},
        { Creatures.Vaporeon.Name, Creatures.Vaporeon},
        { Creatures.Venomoth.Name, Creatures.Venomoth},
        { Creatures.Venonat.Name, Creatures.Venonat},
        { Creatures.Venusaur.Name, Creatures.Venusaur},
        { Creatures.Victreebel.Name, Creatures.Victreebel},
        { Creatures.Vileplume.Name, Creatures.Vileplume},
        { Creatures.Voltorb.Name, Creatures.Voltorb},
        { Creatures.Vulpix.Name, Creatures.Vulpix},
        { Creatures.Wartortle.Name, Creatures.Wartortle},
        { Creatures.Weedle.Name, Creatures.Weedle},
        { Creatures.Weepinbell.Name, Creatures.Weepinbell},
        { Creatures.Weezing.Name, Creatures.Weezing},
        { Creatures.Wigglytuff.Name, Creatures.Wigglytuff},
        { Creatures.Wobbuffet.Name, Creatures.Wobbuffet},
        { Creatures.Wooper.Name, Creatures.Wooper},
        { Creatures.Xatu.Name, Creatures.Xatu},
        { Creatures.Yanma.Name, Creatures.Yanma},
        { Creatures.Zapdos.Name, Creatures.Zapdos},
        { Creatures.Zubat.Name, Creatures.Zubat}
        };
        #endregion
    }
}